import {createHash} from "node:crypto"; import {isClaimStatus,type ClaimStatus} from "./claims";
export type EvidenceEntry={path:string;sha256:string;capturedAt:string;claim:string;status:ClaimStatus;sourceUrl?:string};
export type EvidenceManifest={schema:"signlatch.evidence-manifest.v1";generatedAt:string;entries:EvidenceEntry[];manifestSha256:string};
const secretKeys=/secret|token|password|authorization|cookie|rawBody|documentText|clientSecret/i;
export function sanitizeEvidence(value:unknown):unknown{if(Array.isArray(value))return value.map(sanitizeEvidence); if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).filter(([key])=>!secretKeys.test(key)).map(([key,item])=>[key,sanitizeEvidence(item)])); return value;}
export function evidenceDigest(bytes:Uint8Array){return createHash("sha256").update(bytes).digest("hex");}
export function createEvidenceManifest(entries:EvidenceEntry[],generatedAt:string):EvidenceManifest{for(const e of entries){if(!/^[a-f0-9]{64}$/.test(e.sha256)||!Number.isFinite(Date.parse(e.capturedAt))||!isClaimStatus(e.status)||!e.path||e.path.startsWith("/")||e.path.includes(".."))throw new Error("Evidence entry is invalid"); if(e.sourceUrl&&new URL(e.sourceUrl).protocol!=="https:")throw new Error("Evidence link must use HTTPS");} const sorted=[...entries].sort((a,b)=>a.path.localeCompare(b.path)); const base={schema:"signlatch.evidence-manifest.v1" as const,generatedAt,entries:sorted}; return {...base,manifestSha256:evidenceDigest(Buffer.from(JSON.stringify(base)))};}
export function verifyEvidenceManifest(manifest:EvidenceManifest,files:ReadonlyMap<string,Uint8Array>){const recreated=createEvidenceManifest(manifest.entries,manifest.generatedAt); if(recreated.manifestSha256!==manifest.manifestSha256)throw new Error("Manifest digest mismatch"); for(const entry of manifest.entries){const bytes=files.get(entry.path);if(!bytes||evidenceDigest(bytes)!==entry.sha256)throw new Error(`Evidence digest mismatch: ${entry.path}`);} return true;}
export function privacyFindings(text:string){const patterns=[/-----BEGIN (?:RSA |EC )?PRIVATE KEY-----/i,/\b(?:client_secret|access_token|refresh_token|authorization|cookie)\b\s*[:=]/i,/\b[A-Za-z0-9_-]{24}\.[A-Za-z0-9_-]{24,}\b/,/documentText\s*[:=]/i];return patterns.filter(p=>p.test(text)).map(p=>p.source);}
