import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import test, { after, before, beforeEach } from "node:test";
import postgres from "postgres";
import { createReviewSnapshot } from "../src/core/agreement/review";
import { ApprovalStore } from "../src/server/workflow/approval-store";
import { ESignDispatchStore } from "../src/server/workflow/esign-dispatch-store";
import { ReviewStore } from "../src/server/workflow/review-store";
import { SecurityStore } from "../src/server/workflow/security-store";
import { completeAgreementFixture } from "../tests/fixtures/agreement";

const url = process.env.TEST_DATABASE_URL; if (!url) throw new Error("TEST_DATABASE_URL is required");
const sql = postgres(url, { max: 8 }); const tenant="00000000-0000-4000-8000-000000000041", operator="00000000-0000-4000-8000-000000000042", approver="00000000-0000-4000-8000-000000000043";
before(async()=>{for(const name of ["0002_secure_foundation.sql","0003_agreement_review.sql","0004_exact_approval.sql","0005_esign_dispatch.sql","0007_dispatch_budget_link.sql","0009_esign_retry_schedule.sql","0010_esign_reconciliation_queue.sql"]) await sql.unsafe(readFileSync(new URL(`../migrations/${name}`,import.meta.url),"utf8"));});
beforeEach(async()=>{await sql`truncate esign_dispatches, exact_approvals, review_snapshots, document_versions, agreement_intents, agreement_workflows, provider_operations,provider_budgets,principals, tenants cascade`; await sql`insert into tenants (tenant_id,display_name) values (${tenant},'Dispatch')`; await sql`insert into principals (principal_id,provider,provider_subject,display_name) values (${operator},'github','42','Operator'),(${approver},'github','43','Approver')`;await sql`insert into provider_budgets(tenant_id,provider,operation_kind,period_start,period_end,hard_limit)values(${tenant},'foxit','esign-dispatch',${new Date("2026-08-26T00:00:00Z")},${new Date("2026-08-27T00:00:00Z")},1)`;}); after(async()=>sql.end());

async function ready(){const bytes=Buffer.from("exact artifact"); const sha=createHash("sha256").update(bytes).digest("hex"); const reviews=new ReviewStore(sql); const intent=completeAgreementFixture(); const workflowId=await reviews.createWorkflow(tenant,operator,intent); const snapshot=createReviewSnapshot({workflowId,intent,artifactSha256:sha,recipients:[],fields:[],findings:[],provenanceSha256:"b".repeat(64)}); await reviews.savePreparedReview({workflowId,tenantId:tenant,artifactSha256:sha,actualSize:bytes.length,provenanceSha256:"b".repeat(64),snapshot}); await new ApprovalStore(sql).approveExact({schema:"signlatch.exact-approval.v2",tenantId:tenant,workflowId,reviewVersion:1,reviewDigest:snapshot.digest,approverId:approver,nonce:"dispatch-nonce-0123456789",issuedAt:"2026-08-26T12:00:00Z",expiresAt:"2026-08-26T12:15:00Z"},new Date("2026-08-26T12:05:00Z"));const operation=await new SecurityStore(sql).reserveProviderOperation({tenantId:tenant,kind:"esign-dispatch",idempotencyKey:`dispatch:${snapshot.digest}`,requestDigest:createHash("sha256").update(`${workflowId}:${snapshot.digest}:${sha}`).digest("hex"),now:new Date("2026-08-26T12:05:00Z")}); return {bytes,workflowId,snapshot,operationId:operation.operationId};}
test("approval consumption and dispatch enqueue are atomic and single-use",async()=>{const f=await ready(); const store=new ESignDispatchStore(sql); const now=new Date("2026-08-26T12:05:00Z"); const results=await Promise.allSettled(Array.from({length:8},()=>store.enqueue({workflowId:f.workflowId,tenantId:tenant,expectedReviewDigest:f.snapshot.digest,artifactBytes:f.bytes,operationId:f.operationId,now}))); assert.equal(results.filter(x=>x.status==="fulfilled").length,8);assert.equal(new Set(results.filter(x=>x.status==="fulfilled").map(x=>JSON.stringify(x.value))).size,1); const rows=await sql`select * from esign_dispatches`; assert.equal(rows.length,1);});
test("pre-send artifact rehash denies changed bytes without consuming approval",async()=>{const f=await ready(); await assert.rejects(()=>new ESignDispatchStore(sql).enqueue({workflowId:f.workflowId,tenantId:tenant,expectedReviewDigest:f.snapshot.digest,artifactBytes:Buffer.from("changed"),operationId:f.operationId,now:new Date("2026-08-26T12:05:00Z")}),/Artifact bytes/); const rows=await sql<Array<{consumed_at:Date|null}>>`select consumed_at from exact_approvals`; assert.equal(rows[0].consumed_at,null);});

test("confirmed provider delivery consumes exactly one durable budget unit",async()=>{const f=await ready();const store=new ESignDispatchStore(sql);const now=new Date("2026-08-26T12:05:00Z");await store.enqueue({workflowId:f.workflowId,tenantId:tenant,expectedReviewDigest:f.snapshot.digest,artifactBytes:f.bytes,operationId:f.operationId,now});const lease=await store.leaseNext("worker",now,120,f.workflowId);assert.ok(lease);await store.markSent(lease,"provider-envelope-1","correlation-1");const budgets=await sql`select consumed,reserved from provider_budgets where tenant_id=${tenant} and operation_kind='esign-dispatch'`;assert.deepEqual(Array.from(budgets),[{consumed:1,reserved:0}]);const workflows=await sql`select state from agreement_workflows where workflow_id=${f.workflowId}`;assert.equal(workflows[0].state,"sent");});

test("ambiguous delivery retains the unit until reconciliation finds the existing envelope",async()=>{const f=await ready();const store=new ESignDispatchStore(sql);const now=new Date("2026-08-26T12:05:00Z");const queued=await store.enqueue({workflowId:f.workflowId,tenantId:tenant,expectedReviewDigest:f.snapshot.digest,artifactBytes:f.bytes,operationId:f.operationId,now});const lease=await store.leaseNext("worker",now,120,f.workflowId);assert.ok(lease);await store.markReconcile(lease,"correlation-ambiguous",{phase:"protocol",code:"missing-folder-id"});let budgets=await sql`select consumed,reserved from provider_budgets where tenant_id=${tenant} and operation_kind='esign-dispatch'`;assert.deepEqual(Array.from(budgets),[{consumed:0,reserved:1}]);const operations=await sql`select state,result_payload from provider_operations where operation_id=${f.operationId}`;assert.equal(operations[0].state,"reconcile");assert.deepEqual(operations[0].result_payload,{diagnostic:{phase:"protocol",code:"missing-folder-id"}});let workflows=await sql`select state from agreement_workflows where workflow_id=${f.workflowId}`;assert.equal(workflows[0].state,"reconcile");await store.resolveReconciliation(queued.dispatchId,"provider-existing");budgets=await sql`select consumed,reserved from provider_budgets where tenant_id=${tenant} and operation_kind='esign-dispatch'`;assert.deepEqual(Array.from(budgets),[{consumed:1,reserved:0}]);workflows=await sql`select state from agreement_workflows where workflow_id=${f.workflowId}`;assert.equal(workflows[0].state,"sent");});

test("expired leases move to reconciliation without releasing or consuming budget",async()=>{const f=await ready();const store=new ESignDispatchStore(sql);const now=new Date("2026-08-26T12:05:00Z");await store.enqueue({workflowId:f.workflowId,tenantId:tenant,expectedReviewDigest:f.snapshot.digest,artifactBytes:f.bytes,operationId:f.operationId,now});const lease=await store.leaseNext("dead-worker",now,1,f.workflowId);assert.ok(lease);assert.equal(await store.recoverExpiredLeases(new Date("2026-08-26T12:05:02Z")),1);const dispatches=await sql`select status,leased_by from esign_dispatches where dispatch_id=${lease.dispatch_id}`;assert.deepEqual(Array.from(dispatches),[{status:"reconcile",leased_by:null}]);const operations=await sql`select state,leased_by from provider_operations where operation_id=${f.operationId}`;assert.deepEqual(Array.from(operations),[{state:"reconcile",leased_by:null}]);const budgets=await sql`select consumed,reserved from provider_budgets where tenant_id=${tenant} and operation_kind='esign-dispatch'`;assert.deepEqual(Array.from(budgets),[{consumed:0,reserved:1}]);const workflows=await sql`select state from agreement_workflows where workflow_id=${f.workflowId}`;assert.equal(workflows[0].state,"reconcile");});

test("safe retry honors a durable bounded Retry-After schedule",async()=>{const f=await ready();const store=new ESignDispatchStore(sql);const now=new Date("2026-08-26T12:05:00Z");await store.enqueue({workflowId:f.workflowId,tenantId:tenant,expectedReviewDigest:f.snapshot.digest,artifactBytes:f.bytes,operationId:f.operationId,now});const lease=await store.leaseNext("worker",now,120,f.workflowId);assert.ok(lease);await store.releaseSafeRetry(lease,"rate-limited",now,30_000,{phase:"response",code:"http-429",httpStatus:429});assert.equal(await store.leaseNext("too-early",new Date("2026-08-26T12:05:29Z"),120,f.workflowId),null);const retry=await store.leaseNext("due",new Date("2026-08-26T12:05:30Z"),120,f.workflowId);assert.ok(retry);const operations=await sql`select result_payload from provider_operations where operation_id=${f.operationId}`;assert.deepEqual(operations[0].result_payload,{errorCode:"rate-limited",retryDelayMs:30_000,diagnostic:{phase:"response",code:"http-429",httpStatus:429}});});

test("reconciliation lookup is leased and rescheduled without creating a replacement",async()=>{const f=await ready();const store=new ESignDispatchStore(sql);const now=new Date("2026-08-26T12:05:00Z");await store.enqueue({workflowId:f.workflowId,tenantId:tenant,expectedReviewDigest:f.snapshot.digest,artifactBytes:f.bytes,operationId:f.operationId,now});const dispatch=await store.leaseNext("sender",now,120,f.workflowId);assert.ok(dispatch);await store.markReconcile(dispatch,undefined,{phase:"request",code:"timeout"},now);const lease=await store.leaseNextReconciliation("reconciler",now,120);assert.ok(lease);assert.equal(await store.leaseNextReconciliation("other",now,120),null);await store.releaseUnresolvedReconciliation(lease,now,60_000,"envelope-not-observed");assert.equal(await store.leaseNextReconciliation("early",new Date("2026-08-26T12:05:59Z"),120),null);const due=await store.leaseNextReconciliation("due",new Date("2026-08-26T12:06:00Z"),120);assert.ok(due);assert.equal(due.dispatch_id,dispatch.dispatch_id);});

test("a stale reconciliation lease cannot bind a provider envelope",async()=>{const f=await ready();const store=new ESignDispatchStore(sql);const now=new Date("2026-08-26T12:05:00Z");await store.enqueue({workflowId:f.workflowId,tenantId:tenant,expectedReviewDigest:f.snapshot.digest,artifactBytes:f.bytes,operationId:f.operationId,now});const dispatch=await store.leaseNext("sender",now,120,f.workflowId);assert.ok(dispatch);await store.markReconcile(dispatch,undefined,{phase:"request",code:"timeout"},now);const lease=await store.leaseNextReconciliation("reconciler",now,120);assert.ok(lease);await assert.rejects(()=>store.resolveReconciliation(lease.dispatch_id,"provider-existing",{leasedBy:lease.leasedBy,reconciliation_lease_generation:lease.reconciliation_lease_generation,tenant_id:lease.tenant_id,now:new Date("2026-08-26T12:07:01Z")}),/Reconciliation changed concurrently/);const rows=await sql`select status,provider_envelope_id from esign_dispatches where dispatch_id=${lease.dispatch_id}`;assert.deepEqual(Array.from(rows),[{status:"reconcile",provider_envelope_id:null}]);});

test("confirmed absence closes one ambiguous attempt and releases its reserved unit atomically",async()=>{const f=await ready();const store=new ESignDispatchStore(sql);const now=new Date("2026-08-26T12:05:00Z");await store.enqueue({workflowId:f.workflowId,tenantId:tenant,expectedReviewDigest:f.snapshot.digest,artifactBytes:f.bytes,operationId:f.operationId,now});const lease=await store.leaseNext("sender",now,120,f.workflowId);assert.ok(lease);await store.markReconcile(lease,undefined,{phase:"protocol",code:"missing-folder-id"},now);const evidenceSha256="e".repeat(64);const result=await store.resolveReconciliationAbsent(f.workflowId,evidenceSha256,"auth-2026-08-28-foxit-1");assert.equal(result.status,"failed");const budgets=await sql`select consumed,reserved from provider_budgets where tenant_id=${tenant} and operation_kind='esign-dispatch'`;assert.deepEqual(Array.from(budgets),[{consumed:0,reserved:0}]);const workflows=await sql`select state from agreement_workflows where workflow_id=${f.workflowId}`;assert.equal(workflows[0].state,"failed");const dispatches=await sql`select status from esign_dispatches where workflow_id=${f.workflowId}`;assert.deepEqual(Array.from(dispatches),[{status:"denied"}]);const operations=await sql`select state,result_payload from provider_operations where operation_id=${f.operationId}`;assert.equal(operations[0].state,"failed");assert.equal(operations[0].result_payload.errorCode,"provider-envelope-confirmed-absent");assert.equal(operations[0].result_payload.evidenceSha256,evidenceSha256);assert.match(operations[0].result_payload.authorizationIdHash,/^[0-9a-f]{64}$/);await assert.rejects(()=>store.resolveReconciliationAbsent(f.workflowId,evidenceSha256,"auth-2026-08-28-foxit-1"),/not awaiting reconciliation/);});

test("confirmed absence repairs a legacy dispatching workflow only when dispatch and operation reconcile",async()=>{const f=await ready();const store=new ESignDispatchStore(sql);const now=new Date("2026-08-26T12:05:00Z");await store.enqueue({workflowId:f.workflowId,tenantId:tenant,expectedReviewDigest:f.snapshot.digest,artifactBytes:f.bytes,operationId:f.operationId,now});const lease=await store.leaseNext("sender",now,120,f.workflowId);assert.ok(lease);await store.markReconcile(lease,undefined,{phase:"protocol",code:"missing-folder-id"},now);await sql`update agreement_workflows set state='dispatching' where workflow_id=${f.workflowId}`;await store.resolveReconciliationAbsent(f.workflowId,"f".repeat(64),"auth-legacy-reconcile-2026");const rows=await sql`select state from agreement_workflows where workflow_id=${f.workflowId}`;assert.equal(rows[0].state,"failed");});
